Equipify/smartems/equipmentmanagementsystem/urls.py
# from django.urls import include, path
# from equipmentmanagementsystem import views, adminhodviews, managerhodviews, allocatorhodviews

# app_name = "equipmentmanagementsystem"

# urlpatterns = [

    
# #     path('demo/', views.showDemoPage, name="demo "),
#     # path('get_user_details', views.GetUserDetails , name='getuserdetails'),
#     path('logout', views.logOut, name="logout"),
#     #path('dologin', views.dologin, name="dologin"),
#     path('admin_home', adminhodviews.showAdminPage, name="admin_home"),
    
#     path('add_category', adminhodviews.addCategory, name="add_category"),
#     path('add_inventory', adminhodviews.addNewInventory, name="add_inventory"),
#     path('add_room', adminhodviews.addRoom, name="add_room"),
#     path('add_manager', adminhodviews.addManager, name="add_manager"),
#     path('save_add_manager', adminhodviews.saveAddManager, name="save_add_manager"),
#     path('save_add_category', adminhodviews.saveAddCategory, name="save_add_category"),
# #     path('save_add_inventory', adminhodviews.saveAddInventory, name="save_add_inventory"),
#     path('save_add_room', adminhodviews.saveAddRoom, name="save_add_room"),
#     path('add_equipment', managerhodviews.addEquipment, name="add_equipment"),
#     path('add_allocator', managerhodviews.addAllocator, name="add_allocator"),
#     path('save_add_equipment', managerhodviews.saveAddEquipment, name="save_add_equipment"),
#     path('save_add_allocator', managerhodviews.saveAddAllocator, name="save_add_allocator"),
#     path('view_manager', adminhodviews.viewManager, name="view_manager"),
#     path('view_categories', adminhodviews.viewCategory, name="view_categories"),
# #     path('view_inventories', adminhodviews.viewInventories, name="view_inventories"),
#     path('search_inventory', adminhodviews.searchInventory, name='search_inventory'),
# #     path('filter_inventory', adminhodviews.filterInventory, name='filter_inventory'),
# #     path('view_inventory/<str:inventory_id>', adminhodviews.viewInventory, name="view_inventory"),
# #     path('view_inventory_template', adminhodviews.viewInventoryTemplate, name="view_inventory_template"),
#     path('add_new_inventory', adminhodviews.addNewInventory, name="add_new_inventory"),
#     # path('export_inventory', adminhodviews.exportInventory, name="export_inventory"),
# #     path('equipment_planning_management/', managerhodviews.equipment_planning_management, name='equipment_planning_management'),
# #     path('create_plan/<int:equipment_id>/', managerhodviews.create_plan, name='create_plan'),
#     #path('plan_detail/<int:plan_id>/', managerhodviews.plan_detail, name='plan_detail'),
# #     path('restore_inventory', adminhodviews.restoreInventory, name="restore_inventory"),
#     path('view_rooms', adminhodviews.viewRoom, name="view_rooms"),
# #     path('inventory_save_form', adminhodviews.save_form, name="inventory_save_form"),
# #     path('save_inventory_submit', adminhodviews.save_inventory_submit, name="save_inventory_submit"),
#     path('view_allocator', managerhodviews.viewAllocator, name="view_allocator"),
#     path('view_equipment', managerhodviews.viewEquipment, name="view_equipment"),
#     path('edit_category/<str:category_id>', adminhodviews.editCategory, name="edit_category"),
#     path('edit_room/<str:room_id>', adminhodviews.editRoom, name="edit_room"),
#     path('edit_manager/<str:manager_id>', adminhodviews.editManager, name="edit_manager"),
#     path('save_edit_manager', adminhodviews.saveEditManager, name="save_edit_manager"),
#     path('save_edit_category', adminhodviews.saveEditCategory, name="save_edit_category"),
#     path('save_edit_room', adminhodviews.saveEditRoom, name="save_edit_room"),
#     path('edit_equipment/<str:equipment_id>', managerhodviews.editEquipment, name="edit_equipment"),
#     path('edit_allocator/<str:allocator_id>', managerhodviews.editAllocator, name="edit_allocator"),
#     path('save_edit_allocator', managerhodviews.saveEditAllocator, name="save_edit_allocator"),
#     path('save_edit_equipment', managerhodviews.saveEditEquipment, name="save_edit_equipment"),
#     path('delete_category/<int:category_id>', adminhodviews.deleteCategory, name="delete_category"),
# #     path('delete_inventory/<int:inventory_id>', adminhodviews.deleteInventory, name="delete_inventory"),
#     path('delete_room/<int:room_id>', adminhodviews.deleteRoom, name="delete_room"),
#     path('delete_manager/<int:manager_id>', adminhodviews.deleteManager, name="delete_manager"),
#     path('delete_equipment/<int:equipment_id>', managerhodviews.deleteEquipment,
#          name="delete_equipment"),
#     path('delete_allocator/<int:allocator_id>', managerhodviews.deleteAllocator,
#          name="delete_allocator"),
# #     path('allocator_home', allocatorhodviews.showAllocatorPage, name="allocator_home"),
# #                       path('demo', views.showDemoPage, name="demo"),
#     path('', views.showLoginPage, name="show_login"),
#     path('doLogin', views.doLogin, name="doLogin"),
#     path('get_user_details', views.GetUserDetails),
#     path('logout_user', views.logout_user, name="logout"),
#     path('signup/', views.signaction, name='signaction'),
#     path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
#     path('admin_profile', adminhodviews.admin_profile,name="admin_profile"),
#     path('admin_profile_save', adminhodviews.admin_profile_save,name="admin_profile_save"),
#     path('manager_profile', managerhodviews.manager_profile,name="manager_profile"),
#     path('manager_profile_save', managerhodviews.manager_profile_save,name="manager_profile_save"),

#                   # path('signup_student',views.signup_student,name="signup_student"),
#                   # path('do_researcher_signup',views.do_researcher_signup,name="do_researcher_signup"),
#                   # path('signup_researcher',views.signup_researcher,name="signup_researcher"),
# ]



from django.urls import path
from equipmentmanagementsystem import views, adminhodviews, managerhodviews, researcherhodviews, studenthodviews
from django.urls import include

app_name = "equipmentmanagementsystem"

urlpatterns = [

    
    
    path('logout', views.logOut, name="logout"),
    path('', views.showLoginPage, name="show_login"),
    path('doLogin', views.doLogin, name="doLogin"),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user, name="logout_user"),
    path('admin_home', adminhodviews.showAdminPage, name="admin_home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('researcher_home', researcherhodviews.showResearcherPage, name="researcher_home"),
    path('signaction/', views.signaction, name="signaction"),
    #path('equipment_planning/<int:equipment_id>/', managerhodviews.equipment_planning, name='equipment_planning'),
    #path('equipment_list/', managerhodviews.equipment_list, name='equipment_list'),
    #path('equipment_planning_list/', managerhodviews.equipment_planning_list, name='equipment_planning_list'),
    #path('set_equipment_availability', managerhodviews.set_equipment_availability, name='set_equipment_availability'),
    path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
    path('student_home', studenthodviews.showStudentPage, name="student_home"),
    # path('researcher_home', allocatorhodviews.showResearcherPage, name="researcher_home"),
    path('add_category', adminhodviews.addCategory, name="add_category"),
    #path('add_inventory', adminhodviews.addInventory, name="add_inventory"),
    path('add_room', adminhodviews.addRoom, name="add_room"),
    path('add_manager', adminhodviews.addManager, name="add_manager"),
    path('save_add_manager', adminhodviews.saveAddManager, name="save_add_manager"),
    path('save_add_category', adminhodviews.saveAddCategory, name="save_add_category"),
    #path('save_add_inventory', adminhodviews.saveAddInventory, name="save_add_inventory"),
    path('save_add_room', adminhodviews.saveAddRoom, name="save_add_room"),
    path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
    path('add_equipment', managerhodviews.addEquipment, name="add_equipment"),
    path('add_allocator', managerhodviews.addAllocator, name="add_allocator"),
    path('save_add_equipment', managerhodviews.saveAddEquipment, name="save_add_equipment"),
    path('save_add_allocator', managerhodviews.saveAddAllocator, name="save_add_allocator"),
    path('view_manager', adminhodviews.viewManager, name="view_manager"),
#     path('view_categories', adminhodviews.viewCategory, name="view_categories"),
    #path('view_inventories', adminhodviews.viewInventories, name="view_inventories"),
    path('search_inventory', adminhodviews.searchInventory, name='search_inventory'),
    #path('filter_inventory', adminhodviews.filterInventory, name='filter_inventory'),
    #path('view_inventory/<str:inventory_id>', adminhodviews.viewInventory, name="view_inventory"),
    #path('view_inventory_template', adminhodviews.viewInventoryTemplate, name="view_inventory_template"),
    path('add_new_inventory', adminhodviews.addNewInventory, name="add_new_inventory"),
    path('export_inventory', adminhodviews.exportInventory, name="export_inventory"),
    #path('equipment_planning_management/', managerhodviews.equipment_planning_management, name='equipment_planning_management'),
    #path('create_plan/<int:equipment_id>/', managerhodviews.create_plan, name='create_plan'),
    #path('plan_detail/<int:plan_id>/', managerhodviews.plan_detail, name='plan_detail'),
    #path('restore_inventory', adminhodviews.restoreInventory, name="restore_inventory"),
    path('view_rooms', adminhodviews.viewRoom, name="view_rooms"),
    #path('inventory_save_form', adminhodviews.save_form, name="inventory_save_form"),
    #path('save_inventory_submit', adminhodviews.save_inventory_submit, name="save_inventory_submit"),

Equipify/smartems/smartems/urls.py
# """smartems URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/3.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# # from django.conf.urls.static import static
# # from smartems import settings
# # from django.contrib import admin
# # from django.urls import path, include
# # from equipmentmanagementsystem import views
# # from equipmentmanagementsystem import managerhodviews
# # from equipmentmanagementsystem import adminhodviews

# # from django.urls import path, include
# # from django.contrib.auth import views as auth_views

# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import path, include
# from equipmentmanagementsystem import views, managerhodviews, adminhodviews
# from smartems import settings
# from equipmentmanagementsystem import views
# from equipmentmanagementsystem.views import signaction
# urlpatterns = [
#                   path("", include('equipmentmanagementsystem.urls', namespace='equipmentmanagementsystem')),
#                   path('admin/', admin.site.urls),
#                   path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
#                   path('manager_profile', managerhodviews.manager_profile,name="manager_profile"),
#                   path('manager_profile_save', managerhodviews.manager_profile_save,name="manager_profile_save"),
                  
#                   path('admin_profile', adminhodviews.admin_profile,name="admin_profile"),
#                   path('admin_profile_save', adminhodviews.admin_profile_save,name="admin_profile_save"),
#                 #   path('accounts/', include('django.contrib.auth.urls')),
#                  path('export_inventory', adminhodviews.exportInventory, name="export_inventory"),

#               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
#                                                                                          document_root=settings.STATIC_ROOT)



"""smartems URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from smartems import settings
from django.contrib import admin
from django.urls import path, include
from equipmentmanagementsystem import views
from equipmentmanagementsystem import managerhodviews


urlpatterns = [
                  path("", include('equipmentmanagementsystem.urls', namespace='equipmentmanagementsystem')),
                  path('admin/', admin.site.urls),
                # path('equipment/<int:pk>/qr_code/', managerhodviews.generate_qr_code, name='qr_code'),
                  path('equipment/<int:pk>/qr_code/', managerhodviews.generate_qr_code, name='qr_code'),
              
                 
                path('accounts/',include('django.contrib.auth.urls')),
             
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

Equipify/smartems/equipmentmanagementsystem/templates/error.html
<h1>Error Page</h1>

Equipify/smartems/equipmentmanagementsystem/templates/login_page.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Equipify System Login</title>

  
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

   
    <link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">

</head>

<body class="bg-dark d-flex align-items-center justify-content-center vh-100r">

    <div class="container mt-5  pt-5  ">

      
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                       
                        <div class="row">
                            
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <img class="mb-4" src="{% static "colored logo.png" %}" alt="" width="200px" height="ml-auto">
                                    </div>
                                  
                                    <form  class="user" action="/doLogin" method="POST" >
                                        {% csrf_token%}
                                        <div class="form-outline form-white mb-4">
                                            <input required type="text" name="email_or_username" class="form-control form-control-lg"
                                            placeholder="Email or Username"/>
                                            
                                          </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control form-control-lg" name="password"
                                                 placeholder="Password">
                                        </div>
                                        
                                        <div class="form-group mt-4">
                                            <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
                                          </div>
                                          <div class="form-group">
                                            {% if messages %}
                                              {% for message in messages %}
                                              {% if message.tags == 'error' %}
                                              <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                                              {% endif %}
                                              {% if message.tags == 'success' %}
                                              <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                                              {% endif %}
                                              {% endfor %}
                                            {% endif %}
                                          </div>
                                      
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small"  href="{% url 'equipmentmanagementsystem:password_reset' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'equipmentmanagementsystem:signaction' %}">Create an Account!</a>
                                    </div>
                                    
                                </div>
                            </div>
                            <!--the image of the brand-->
                            <div class="col-lg-6 mt-4">

                                <img class=" rounded m-" src="{% static "login side picture .png" %}" alt="" height="410px" width="ml-auto" >

                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static "js/sb-admin-2.min.js" %}"></script>


</body>

</html>

Equipify/smartems/equipmentmanagementsystem/templates/qr_code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QR Code</title>
    <style>
        .qr-code-container {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="qr-code-container">
        <h2>Equipment Details</h2>
        <p>The equipment code is: {{ equipment.code }}</p>
        <p>The equipment room is: {{ equipment.room_id.name }}</p>
        <p>Total number is: {{ equipment.totalnumber }}</p>
        <img src="{{ qr_code_url }}" alt="QR Code">
        <br>
        <button id="printButton">Print QR Code</button>
    </div>
    <script>
        document.getElementById('printButton').addEventListener('click', function() {
            window.print();
        });
    </script>
</body>
</html>

Equipify/smartems/equipmentmanagementsystem/templates/signup_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Equipify System Signup</title>

    
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

   
    <link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">

</head>

<body class="bg-dark mt-5 pt-2">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <img class="mb-4" src="{% static "colored logo.png" %}" alt="" width="200px" height="ml-auto">
                            </div>
                            <div class="text-center font-weight-bold">
                                <h1 class="h4 text-gray-900 mb-4 font-weight-bold">SIGN UP</h1>
                            </div>
                            <form action="/signaction/" method="post" class="user" >
                                          {% csrf_token %}
                                          <div class="form-group row">
                                            <div class="col-sm-6 mb-3 mb-sm-0">
                                                <input type="text" class="form-control form-control-user" id="exampleFirstName"
                                                    placeholder="Full Name" name="fullname">
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="number" class="form-control form-control-user" id="exampleLastName"
                                                    placeholder="Phone Number" name="phonenumber">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                                placeholder="Email Address" name="email">
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-sm-6 mb-3 mb-sm-0">
                                                <input type="text" class="form-control form-control-user"
                                                    id="exampleInputPassword" placeholder="Username" name="username">
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="password" class="form-control form-control-user"
                                                    id="exampleRepeatPassword" placeholder="Password" name="password">
                                            </div>
                                        </div>
                               
                                <div class="form-check form-check-inline mt-3">
                <input class="form-check-input" type="radio" name="role" id="exampleRadios1" value="student" required>
                <label class="form-check-label" for="exampleRadios1">
                    Student
                </label>
                </div>
                <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="role" id="exampleRadios2" value="researcher" required>
                <label class="form-check-label" for="exampleRadios2">
                    Researcher
                </label>
                </div><button type="submit" class="btn btn-primary btn-user btn-block"> Sign up </button>
                                    
                                    <hr>
                                    <div class="text-center">
                                    Already have an account?<a class="small" href="{% url 'equipmentmanagementsystem:show_login' %}"> Login</a>
                                </div>
                                </form>
                                <hr>
                       
                          
                        </div>
                    </div>
                    <!--the image of the brand-->
                    <div class="col-lg-4 mt-5">

                        <img class=" rounded m-" src="{% static "login side picture .png" %}"  alt="" height="410px" width="ml-auto" >

                </div>
            </div>
        </div>

    </div>

   
    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static "js/sb-admin-2.min.js" %}"></script>



</body>

</html>