Equipify/smartems/equipmentmanagementsystem/urls.py
# from django.urls import include, path
# from equipmentmanagementsystem import views, adminhodviews, managerhodviews, allocatorhodviews

# app_name = "equipmentmanagementsystem"

# urlpatterns = [

    
# #     path('demo/', views.showDemoPage, name="demo "),
#     # path('get_user_details', views.GetUserDetails , name='getuserdetails'),
#     path('logout', views.logOut, name="logout"),
#     #path('dologin', views.dologin, name="dologin"),
#     path('admin_home', adminhodviews.showAdminPage, name="admin_home"),
    
#     path('add_category', adminhodviews.addCategory, name="add_category"),
#     path('add_inventory', adminhodviews.addNewInventory, name="add_inventory"),
#     path('add_room', adminhodviews.addRoom, name="add_room"),
#     path('add_manager', adminhodviews.addManager, name="add_manager"),
#     path('save_add_manager', adminhodviews.saveAddManager, name="save_add_manager"),
#     path('save_add_category', adminhodviews.saveAddCategory, name="save_add_category"),
# #     path('save_add_inventory', adminhodviews.saveAddInventory, name="save_add_inventory"),
#     path('save_add_room', adminhodviews.saveAddRoom, name="save_add_room"),
#     path('add_equipment', managerhodviews.addEquipment, name="add_equipment"),
#     path('add_allocator', managerhodviews.addAllocator, name="add_allocator"),
#     path('save_add_equipment', managerhodviews.saveAddEquipment, name="save_add_equipment"),
#     path('save_add_allocator', managerhodviews.saveAddAllocator, name="save_add_allocator"),
#     path('view_manager', adminhodviews.viewManager, name="view_manager"),
#     path('view_categories', adminhodviews.viewCategory, name="view_categories"),
# #     path('view_inventories', adminhodviews.viewInventories, name="view_inventories"),
#     path('search_inventory', adminhodviews.searchInventory, name='search_inventory'),
# #     path('filter_inventory', adminhodviews.filterInventory, name='filter_inventory'),
# #     path('view_inventory/<str:inventory_id>', adminhodviews.viewInventory, name="view_inventory"),
# #     path('view_inventory_template', adminhodviews.viewInventoryTemplate, name="view_inventory_template"),
#     path('add_new_inventory', adminhodviews.addNewInventory, name="add_new_inventory"),
#     # path('export_inventory', adminhodviews.exportInventory, name="export_inventory"),
# #     path('equipment_planning_management/', managerhodviews.equipment_planning_management, name='equipment_planning_management'),
# #     path('create_plan/<int:equipment_id>/', managerhodviews.create_plan, name='create_plan'),
#     #path('plan_detail/<int:plan_id>/', managerhodviews.plan_detail, name='plan_detail'),
# #     path('restore_inventory', adminhodviews.restoreInventory, name="restore_inventory"),
#     path('view_rooms', adminhodviews.viewRoom, name="view_rooms"),
# #     path('inventory_save_form', adminhodviews.save_form, name="inventory_save_form"),
# #     path('save_inventory_submit', adminhodviews.save_inventory_submit, name="save_inventory_submit"),
#     path('view_allocator', managerhodviews.viewAllocator, name="view_allocator"),
#     path('view_equipment', managerhodviews.viewEquipment, name="view_equipment"),
#     path('edit_category/<str:category_id>', adminhodviews.editCategory, name="edit_category"),
#     path('edit_room/<str:room_id>', adminhodviews.editRoom, name="edit_room"),
#     path('edit_manager/<str:manager_id>', adminhodviews.editManager, name="edit_manager"),
#     path('save_edit_manager', adminhodviews.saveEditManager, name="save_edit_manager"),
#     path('save_edit_category', adminhodviews.saveEditCategory, name="save_edit_category"),
#     path('save_edit_room', adminhodviews.saveEditRoom, name="save_edit_room"),
#     path('edit_equipment/<str:equipment_id>', managerhodviews.editEquipment, name="edit_equipment"),
#     path('edit_allocator/<str:allocator_id>', managerhodviews.editAllocator, name="edit_allocator"),
#     path('save_edit_allocator', managerhodviews.saveEditAllocator, name="save_edit_allocator"),
#     path('save_edit_equipment', managerhodviews.saveEditEquipment, name="save_edit_equipment"),
#     path('delete_category/<int:category_id>', adminhodviews.deleteCategory, name="delete_category"),
# #     path('delete_inventory/<int:inventory_id>', adminhodviews.deleteInventory, name="delete_inventory"),
#     path('delete_room/<int:room_id>', adminhodviews.deleteRoom, name="delete_room"),
#     path('delete_manager/<int:manager_id>', adminhodviews.deleteManager, name="delete_manager"),
#     path('delete_equipment/<int:equipment_id>', managerhodviews.deleteEquipment,
#          name="delete_equipment"),
#     path('delete_allocator/<int:allocator_id>', managerhodviews.deleteAllocator,
#          name="delete_allocator"),
# #     path('allocator_home', allocatorhodviews.showAllocatorPage, name="allocator_home"),
# #                       path('demo', views.showDemoPage, name="demo"),
#     path('', views.showLoginPage, name="show_login"),
#     path('doLogin', views.doLogin, name="doLogin"),
#     path('get_user_details', views.GetUserDetails),
#     path('logout_user', views.logout_user, name="logout"),
#     path('signup/', views.signaction, name='signaction'),
#     path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
#     path('admin_profile', adminhodviews.admin_profile,name="admin_profile"),
#     path('admin_profile_save', adminhodviews.admin_profile_save,name="admin_profile_save"),
#     path('manager_profile', managerhodviews.manager_profile,name="manager_profile"),
#     path('manager_profile_save', managerhodviews.manager_profile_save,name="manager_profile_save"),

#                   # path('signup_student',views.signup_student,name="signup_student"),
#                   # path('do_researcher_signup',views.do_researcher_signup,name="do_researcher_signup"),
#                   # path('signup_researcher',views.signup_researcher,name="signup_researcher"),
# ]



from django.urls import path
from equipmentmanagementsystem import views, adminhodviews, managerhodviews, researcherhodviews, studenthodviews
from django.urls import include

app_name = "equipmentmanagementsystem"

urlpatterns = [

    
    
    path('logout', views.logOut, name="logout"),
    path('', views.showLoginPage, name="show_login"),
    path('doLogin', views.doLogin, name="doLogin"),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user, name="logout_user"),
    path('admin_home', adminhodviews.showAdminPage, name="admin_home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('researcher_home', researcherhodviews.showResearcherPage, name="researcher_home"),
    path('signaction/', views.signaction, name="signaction"),
    #path('equipment_planning/<int:equipment_id>/', managerhodviews.equipment_planning, name='equipment_planning'),
    #path('equipment_list/', managerhodviews.equipment_list, name='equipment_list'),
    #path('equipment_planning_list/', managerhodviews.equipment_planning_list, name='equipment_planning_list'),
    #path('set_equipment_availability', managerhodviews.set_equipment_availability, name='set_equipment_availability'),
    path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
    path('student_home', studenthodviews.showStudentPage, name="student_home"),
    # path('researcher_home', allocatorhodviews.showResearcherPage, name="researcher_home"),
    path('add_category', adminhodviews.addCategory, name="add_category"),
    #path('add_inventory', adminhodviews.addInventory, name="add_inventory"),
    path('add_room', adminhodviews.addRoom, name="add_room"),
    path('add_manager', adminhodviews.addManager, name="add_manager"),
    path('save_add_manager', adminhodviews.saveAddManager, name="save_add_manager"),
    path('save_add_category', adminhodviews.saveAddCategory, name="save_add_category"),
    #path('save_add_inventory', adminhodviews.saveAddInventory, name="save_add_inventory"),
    path('save_add_room', adminhodviews.saveAddRoom, name="save_add_room"),
    path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
    path('add_equipment', managerhodviews.addEquipment, name="add_equipment"),
    path('add_allocator', managerhodviews.addAllocator, name="add_allocator"),
    path('save_add_equipment', managerhodviews.saveAddEquipment, name="save_add_equipment"),
    path('save_add_allocator', managerhodviews.saveAddAllocator, name="save_add_allocator"),
    path('view_manager', adminhodviews.viewManager, name="view_manager"),
#     path('view_categories', adminhodviews.viewCategory, name="view_categories"),
    #path('view_inventories', adminhodviews.viewInventories, name="view_inventories"),
    path('search_inventory', adminhodviews.searchInventory, name='search_inventory'),
    #path('filter_inventory', adminhodviews.filterInventory, name='filter_inventory'),
    #path('view_inventory/<str:inventory_id>', adminhodviews.viewInventory, name="view_inventory"),
    #path('view_inventory_template', adminhodviews.viewInventoryTemplate, name="view_inventory_template"),
    path('add_new_inventory', adminhodviews.addNewInventory, name="add_new_inventory"),
    path('export_inventory', adminhodviews.exportInventory, name="export_inventory"),
    #path('equipment_planning_management/', managerhodviews.equipment_planning_management, name='equipment_planning_management'),
    #path('create_plan/<int:equipment_id>/', managerhodviews.create_plan, name='create_plan'),
    #path('plan_detail/<int:plan_id>/', managerhodviews.plan_detail, name='plan_detail'),
    #path('restore_inventory', adminhodviews.restoreInventory, name="restore_inventory"),
    path('view_rooms', adminhodviews.viewRoom, name="view_rooms"),
    #path('inventory_save_form', adminhodviews.save_form, name="inventory_save_form"),
    #path('save_inventory_submit', adminhodviews.save_inventory_submit, name="save_inventory_submit"),

Equipify/smartems/smartems/urls.py
# """smartems URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/3.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# # from django.conf.urls.static import static
# # from smartems import settings
# # from django.contrib import admin
# # from django.urls import path, include
# # from equipmentmanagementsystem import views
# # from equipmentmanagementsystem import managerhodviews
# # from equipmentmanagementsystem import adminhodviews

# # from django.urls import path, include
# # from django.contrib.auth import views as auth_views

# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import path, include
# from equipmentmanagementsystem import views, managerhodviews, adminhodviews
# from smartems import settings
# from equipmentmanagementsystem import views
# from equipmentmanagementsystem.views import signaction
# urlpatterns = [
#                   path("", include('equipmentmanagementsystem.urls', namespace='equipmentmanagementsystem')),
#                   path('admin/', admin.site.urls),
#                   path('manager_home', managerhodviews.showManagerPage, name="manager_home"),
#                   path('manager_profile', managerhodviews.manager_profile,name="manager_profile"),
#                   path('manager_profile_save', managerhodviews.manager_profile_save,name="manager_profile_save"),
                  
#                   path('admin_profile', adminhodviews.admin_profile,name="admin_profile"),
#                   path('admin_profile_save', adminhodviews.admin_profile_save,name="admin_profile_save"),
#                 #   path('accounts/', include('django.contrib.auth.urls')),
#                  path('export_inventory', adminhodviews.exportInventory, name="export_inventory"),

#               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
#                                                                                          document_root=settings.STATIC_ROOT)



"""smartems URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from smartems import settings
from django.contrib import admin
from django.urls import path, include
from equipmentmanagementsystem import views
from equipmentmanagementsystem import managerhodviews


urlpatterns = [
                  path("", include('equipmentmanagementsystem.urls', namespace='equipmentmanagementsystem')),
                  path('admin/', admin.site.urls),
                # path('equipment/<int:pk>/qr_code/', managerhodviews.generate_qr_code, name='qr_code'),
                  path('equipment/<int:pk>/qr_code/', managerhodviews.generate_qr_code, name='qr_code'),
              
                 
                path('accounts/',include('django.contrib.auth.urls')),
             
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/add_allocation.html
{% extends "managerhod_templates/base_template.html" %}
{% block page_title %}
   Add Allocation
{% endblock page_title %}
{% block main_content %}
<div class="container-fluid">
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              
                <div class="row">
                      <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Add New Allocation</h1>
                            </div>
                             {% url 'equipmentmanagementsystem:add_allocation' as action_path %}
                             {% include 'managerhod_templates/form_template.html' with messages=messages form=form action_path=action_path button_text="Add Equipment Allocation"  %}
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/add_allocator.html
{% extends "managerhod_templates/base_template.html" %}
{% block page_title %}
   Add Allocator
{% endblock page_title %}
{% block main_content %}
<div class="container-fluid">
   <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                
                <div class="row">

                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Add New Allocator</h1>
                            </div>

                               {% url 'equipmentmanagementsystem:save_add_allocator' as action_path %}
                               {% include 'managerhod_templates/form_template.html' with messages=messages form=form action_path=action_path button_text="Add Allocator"  %}


                       </div>
                    </div>
                </div>
            </div>

       </div>
   </div>
</div>
{% endblock main_content %}

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/add_equipment.html
{% extends "managerhod_templates/base_template.html" %}
{% block page_title %}
   Add Equipment
{% endblock page_title %}
{% block main_content %}
<div class="container-fluid">
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
             
                <div class="row">
                      <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Add New Equipment</h1>
                            </div>
                             {% url 'equipmentmanagementsystem:save_add_equipment' as action_path %}
                             {% include 'managerhod_templates/form_template.html' with messages=messages form=form action_path=action_path button_text="Add Equipment"  %}
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/edit_allocator.html
{% extends "managerhod_templates/base_template.html" %}
{% block page_title %}
   Edit Allocator
{% endblock page_title %}
{% block main_content %}
<div class="container-fluid">
     <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              
                <div class="row">
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Edit Allocator Details</h1>
                            </div>
                             {% url 'equipmentmanagementsystem:save_edit_allocator' as action_path %}
                            {% include 'managerhod_templates/form_template.html' with messages=messages form=form action_path=action_path button_text="Edit Allocator"  %}
                    </div>
                </div>
            </div>
        </div>
        </div>
     </div>
</div>
{% endblock main_content %}

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/edit_equipment.html
{% extends "managerhod_templates/base_template.html" %}
{% block page_title %}
   Edit Equipment
{% endblock page_title %}
{% block main_content %}
<div class="container-fluid">
  <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              
                <div class="row">
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Edit Equipment Informations</h1>
                            </div>
                            {% url 'equipmentmanagementsystem:save_edit_equipment' as action_path %}
                            {% include 'managerhod_templates/form_template.html' with messages=messages form=form action_path=action_path button_text="Edit Equipment"  %}

                       </div>
                 </div>
             </div>
           </div>
        </div>
  </div>
</div>
{% endblock main_content %}

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/form_template.html
<form role = "form" action = "{{ action_path }}" method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="card-body">
{% for field in form %}
            <div class="form-group row">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
         </div>
            {% endfor %}
   <div class="form-group row">
    {% if messages %}
            <div class="form-group">
                {% for message in messages %}
                {% if message.tags == "error" %}
                <span class = "alert alert-danger">{{ message }}</span>
                {% endif %}
                {% if message.tags == "success" %}
                <span class = "alert alert-success">{{ message }}</span>
                 {% endif %}
                 {% endfor %}
            </div>
    {% endif %}
     </div>
</div>
      <div class="card-footer">
      <button type = "submit"  class="btn btn-primary btn-block ">
          {{ button_text }}
    </button>
          </div>
</form>

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/manager_profile.html
{% extends 'managerhod_templates/base_template.html' %}
{% block page_title %}
Edit Profile
{% endblock page_title %}
{% block main_content %}
 
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
           
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Profile</h3>
              </div>
       
              <form role="form" action="{% url 'equipmentmanagementsystem:manager_profile_save' %}" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.username }}" disabled="disabled">
                  </div>
                  <div class="form-group">
                    <label>email</label>
                    <input type="text" class="form-control" name="email" value="{{ user.email }}">
                  </div>
                   <div class="form-group">
                    <label>fullname</label>
                    <input type="text" class="form-control" name="fullname" value="{{ manager.fullname }}">
                  </div>
                    <div class="form-group">
                    <label>phone number</label>
                    <input type="text" class="form-control" name="phonenumber" value="{{ manager.phonenumber }}">
                  </div>
                   <div class="form-group">
                    <label>Change Password?</label>
                    <input type="text" class="form-control" name="password" placeholder="Fill directly with the new password, you will be redirected to the login page!">
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
 

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Save Profile</button>
                </div>
              </form>
            </div>




          </div>
          </div>
      </div>
    </section>

{% endblock main_content %}

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/manager_profile_save.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/view_allocation.html
{% extends "managerhod_templates/base_template.html" %}
{% block page_title %}
   Equipment Allocation List
{% endblock page_title %}
{% block main_content %}
<div class="container-fluid">
    <div class="container">
   
         
                       <div class="card shadow mb-4">
                           
                           <div class="card-header py-3">
                               <h6 class="m-0 font-weight-bold text-primary">Equipments Allocation List</h6>
                           </div>
                           <div class="card-body">
                               <div class="table-responsive">
                                   <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                       <thead>
            <tr>
                <th>Id</th>
                <th>Allocator</th>
                <th>Equipment</th>
                <th>DateTime</th>
                <th>Deadline</th>
             
            </tr>
        </thead>
        <tbody>
            {% for equipment_allocation in equipment_allocations %}
            <tr>
                <td>{{ equipment_allocation.id }}</td>
                <td>{{ equipment_allocation.allocator.fullname }}</td>
                <td>{{ equipment_allocation.equipment.name }}</td>
                <td>{{ equipment_allocation.start_datetime }}</td>
                <td>{{ equipment_allocation.end_datetime }}</td>
                
                     
                 </tr>
        {% endfor %}
        </tbody>

    </table>
</div>
</div>
</div>

</div>


</div>


</div>
</div>
{% endblock main_content %}

Equipify/smartems/equipmentmanagementsystem/templates/managerhod_templates/view_equipment_planning.html
{% extends "managerhod_templates/base_template.html" %}
{% block page_title %}
   Equipment Planning List
{% endblock page_title %}
{% block main_content %}
<div class="container-fluid">
    <div class="container">
   
           
                       <div class="card shadow mb-4">
                           
                           <div class="card-header py-3">
                               <h6 class="m-0 font-weight-bold text-primary">Equipments Planning List</h6>
                           </div>
                           
                           <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success">{{ message }}</div>
                                {% endfor %}
                            {% endif %}
                            <form method="post" action="/export_planning">
                                {% csrf_token %}
                                Please select one of the appeared options: 
                                <label><input type="radio" name="format" value="csv"> CSV</label>
                                <label><input type="radio" name="format" value="pdf"> PDF</label>
                                <label><input type="radio" name="format" value="xls"> XLS</label>
                                <label for="filename">You can choose filename if you want:</label>
                                <input type="text" name="filename" id="filename">
                                <button class="btn bg-dark text-white mb-3" type="submit">Export</button>
                            </form>
                               <div class="table-responsive">
                                   <a class="btn bg-dark text-white mb-3" href="/add_equipment_planning">Add new equipment planning</a>
                                   <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                       <thead>
            <tr>
                <th>Id</th>
                <th>Equipment</th>
                <th>Day</th>
                
                <th>Start Time</th>
                <th>End Time</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for equipment_planning in equipment_plannings %}
            <tr>
                <td>{{ equipment_planning.id }}</td>
                <td>{{ equipment_planning.equipment.name }}</td>
                <td>{{ equipment_planning.get_day_display }}</td>
                
                <td>{{ equipment_planning.start_time }}</td>
                <td>{{ equipment_planning.end_time }}</td>
                <td><a class="" id="edit" href="/edit_equipment_planning/{{ equipment_planning.id }}"><i class=" fas fa-pencil-alt"></i></a>
                    <a class="m-sm-4" href="/delete_equipment_planning/{{ equipment_planning.id }}"><i class=" fas fa-minus-circle fa-sm"></i></a>
                </td>
                     
                 </tr>
        {% endfor %}
        </tbody>

    </table>
</div>
</div>
</div>

</div>


</div>


</div>
</div>
{% endblock main_content %}